/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.userfsb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Userf service. Represents a row in the &quot;Userf_Userf&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.test.userfsb.model.impl.UserfModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.test.userfsb.model.impl.UserfImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Userf
 * @generated
 */
@ProviderType
public interface UserfModel extends BaseModel<Userf> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a userf model instance should use the {@link Userf} interface instead.
	 */

	/**
	 * Returns the primary key of this userf.
	 *
	 * @return the primary key of this userf
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this userf.
	 *
	 * @param primaryKey the primary key of this userf
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this userf.
	 *
	 * @return the uuid of this userf
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this userf.
	 *
	 * @param uuid the uuid of this userf
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this userf.
	 *
	 * @return the ID of this userf
	 */
	public long getId();

	/**
	 * Sets the ID of this userf.
	 *
	 * @param id the ID of this userf
	 */
	public void setId(long id);

	/**
	 * Returns the name of this userf.
	 *
	 * @return the name of this userf
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this userf.
	 *
	 * @param name the name of this userf
	 */
	public void setName(String name);

	/**
	 * Returns the surname of this userf.
	 *
	 * @return the surname of this userf
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this userf.
	 *
	 * @param surname the surname of this userf
	 */
	public void setSurname(String surname);

	/**
	 * Returns the email of this userf.
	 *
	 * @return the email of this userf
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this userf.
	 *
	 * @param email the email of this userf
	 */
	public void setEmail(String email);

	/**
	 * Returns the birthdate of this userf.
	 *
	 * @return the birthdate of this userf
	 */
	public Date getBirthdate();

	/**
	 * Sets the birthdate of this userf.
	 *
	 * @param birthdate the birthdate of this userf
	 */
	public void setBirthdate(Date birthdate);

	/**
	 * Returns the creationdate of this userf.
	 *
	 * @return the creationdate of this userf
	 */
	public Date getCreationdate();

	/**
	 * Sets the creationdate of this userf.
	 *
	 * @param creationdate the creationdate of this userf
	 */
	public void setCreationdate(Date creationdate);

}